version: 2
updates:
  - package-ecosystem: maven
    assignees:
      - dflippojr
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: [dependencies]
    groups:
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
  - package-ecosystem: github-actions
    assignees:
      - dflippojr
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: [dependencies]
