sonar.projectKey=fhir-crd-router
sonar.projectName=fhir-crd-router
sonar.sourceEncoding=UTF-8
sonar.sources=directory-core/src/main/java,credential-store-encrypted-local/src/main/java,client-sdk/src/main/java,examples-quickstart/src/main/java
sonar.tests=directory-core/src/test/java,credential-store-encrypted-local/src/test/java,client-sdk/src/test/java
sonar.java.binaries=directory-core/target/classes,credential-store-encrypted-local/target/classes,client-sdk/target/classes,examples-quickstart/target/classes
sonar.java.test.binaries=directory-core/target/test-classes,credential-store-encrypted-local/target/test-classes,client-sdk/target/test-classes
